spring:
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: true
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usermanagement
    hikari:
      schema: usermanagement
      username: postgres
      password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: usermanagement
        jdbc:
         time_zone: UTC
